-- NOTE: This file is auto generated by ./sql-generator

-- DuplicateRepository.getAll
with
  "duplicates" as (
    select
      "asset"."duplicateId",
      json_agg(
        "asset2"
        order by
          "asset"."localDateTime" asc
      ) as "assets"
    from
      "asset"
      inner join lateral (
        select
          "asset".*,
          to_json("asset_exif") as "exifInfo",
          (
            select
              coalesce(json_agg(agg), '[]')
            from
              (
                select
                  "tag"."id",
                  "tag"."value",
                  "tag"."createdAt",
                  "tag"."updatedAt",
                  "tag"."color",
                  "tag"."parentId"
                from
                  "tag"
                  inner join "tag_asset" on "tag"."id" = "tag_asset"."tagId"
                where
                  "tag_asset"."assetId" = "asset"."id"
              ) as agg
          ) as "tags"
        from
          "asset_exif"
        where
          "asset_exif"."assetId" = "asset"."id"
      ) as "asset2" on true
    where
      "asset"."visibility" in ('archive', 'timeline')
      and "asset"."ownerId" = $1::uuid
      and "asset"."duplicateId" is not null
      and "asset"."deletedAt" is null
      and "asset"."stackId" is null
    group by
      "asset"."duplicateId"
  )
select
  *
from
  "duplicates"
where
  json_array_length("assets") > $2

-- DuplicateRepository.cleanupSingletonGroups
with
  "singletons" as (
    select
      "duplicateId"
    from
      "asset"
    where
      "ownerId" = $1::uuid
      and "duplicateId" is not null
      and "deletedAt" is null
      and "stackId" is null
    group by
      "duplicateId"
    having
      count("id") = $2
  )
update "asset"
set
  "duplicateId" = $3
from
  "singletons"
where
  "asset"."duplicateId" = "singletons"."duplicateId"

-- DuplicateRepository.get
select
  "asset"."duplicateId",
  json_agg(
    "asset2"
    order by
      "asset"."localDateTime" asc
  ) as "assets"
from
  "asset"
  inner join lateral (
    select
      "asset".*,
      to_json("asset_exif") as "exifInfo",
      (
        select
          coalesce(json_agg(agg), '[]')
        from
          (
            select
              "tag"."id",
              "tag"."value",
              "tag"."createdAt",
              "tag"."updatedAt",
              "tag"."color",
              "tag"."parentId"
            from
              "tag"
              inner join "tag_asset" on "tag"."id" = "tag_asset"."tagId"
            where
              "tag_asset"."assetId" = "asset"."id"
          ) as agg
      ) as "tags"
    from
      "asset_exif"
    where
      "asset_exif"."assetId" = "asset"."id"
  ) as "asset2" on true
where
  "asset"."visibility" in ('archive', 'timeline')
  and "asset"."duplicateId" = $1::uuid
  and "asset"."deletedAt" is null
  and "asset"."stackId" is null
group by
  "asset"."duplicateId"

-- DuplicateRepository.streamForAutoStack
select
  "asset"."id"
from
  "asset"
where
  "asset"."type" = $1
  and "asset"."visibility" in ($2, $3)
  and "asset"."deletedAt" is null
  and "asset"."stackId" is null
  and lower(asset."originalFileName") like any (
    array[
      '%.jpg',
      '%.jpeg',
      '%.jpe',
      '%.png',
      '%.3fr',
      '%.ari',
      '%.arw',
      '%.cap',
      '%.cin',
      '%.cr2',
      '%.cr3',
      '%.crw',
      '%.dcr',
      '%.dng',
      '%.erf',
      '%.fff',
      '%.iiq',
      '%.k25',
      '%.kdc',
      '%.mrw',
      '%.nef',
      '%.nrw',
      '%.orf',
      '%.ori',
      '%.pef',
      '%.psd',
      '%.raf',
      '%.raw',
      '%.rw2',
      '%.rwl',
      '%.sr2',
      '%.srf',
      '%.srw',
      '%.x3f'
    ]::text[]
  )
  and exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $4
      and "asset_file"."isEdited" = $5
  )

-- DuplicateRepository.getAutoStackSeed
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."originalFileName",
  "asset"."type",
  "asset"."visibility",
  "asset"."stackId",
  "asset"."duplicateId",
  "asset"."localDateTime",
  "asset_exif"."fileSizeInByte",
  "asset_exif"."dateTimeOriginal",
  "asset_exif"."make",
  "asset_exif"."model",
  "asset_exif"."lensModel",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'preview'
      and "asset_file"."isEdited" = false
  ) as "previewPath"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."id" = $1::uuid
  and "asset"."type" = $2
  and "asset"."visibility" in ($3, $4)
  and "asset"."deletedAt" is null
  and "asset"."stackId" is null

-- DuplicateRepository.getAutoStackCandidates
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."originalFileName",
  "asset"."type",
  "asset"."visibility",
  "asset"."stackId",
  "asset"."duplicateId",
  "asset"."localDateTime",
  "asset_exif"."fileSizeInByte",
  "asset_exif"."dateTimeOriginal",
  "asset_exif"."make",
  "asset_exif"."model",
  "asset_exif"."lensModel",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'preview'
      and "asset_file"."isEdited" = false
  ) as "previewPath"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."id" != $1::uuid
  and "asset"."ownerId" = $2::uuid
  and "asset"."type" = $3
  and "asset"."visibility" in ($4, $5)
  and "asset"."deletedAt" is null
  and "asset"."stackId" is null
  and lower(asset."originalFileName") like any (
    array[
      '%.jpg',
      '%.jpeg',
      '%.jpe',
      '%.png',
      '%.3fr',
      '%.ari',
      '%.arw',
      '%.cap',
      '%.cin',
      '%.cr2',
      '%.cr3',
      '%.crw',
      '%.dcr',
      '%.dng',
      '%.erf',
      '%.fff',
      '%.iiq',
      '%.k25',
      '%.kdc',
      '%.mrw',
      '%.nef',
      '%.nrw',
      '%.orf',
      '%.ori',
      '%.pef',
      '%.psd',
      '%.raf',
      '%.raw',
      '%.rw2',
      '%.rwl',
      '%.sr2',
      '%.srf',
      '%.srw',
      '%.x3f'
    ]::text[]
  )
  and exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $6
      and "asset_file"."isEdited" = $7
  )
  and "asset"."localDateTime" >= $8
  and "asset"."localDateTime" <= $9
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."originalFileName",
  "asset"."type",
  "asset"."visibility",
  "asset"."stackId",
  "asset"."duplicateId",
  "asset"."localDateTime",
  "asset_exif"."fileSizeInByte",
  "asset_exif"."dateTimeOriginal",
  "asset_exif"."make",
  "asset_exif"."model",
  "asset_exif"."lensModel",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'preview'
      and "asset_file"."isEdited" = false
  ) as "previewPath"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."id" != $1::uuid
  and "asset"."ownerId" = $2::uuid
  and "asset"."type" = $3
  and "asset"."visibility" in ($4, $5)
  and "asset"."deletedAt" is null
  and "asset"."stackId" is null
  and lower(asset."originalFileName") like any (
    array[
      '%.jpg',
      '%.jpeg',
      '%.jpe',
      '%.png',
      '%.3fr',
      '%.ari',
      '%.arw',
      '%.cap',
      '%.cin',
      '%.cr2',
      '%.cr3',
      '%.crw',
      '%.dcr',
      '%.dng',
      '%.erf',
      '%.fff',
      '%.iiq',
      '%.k25',
      '%.kdc',
      '%.mrw',
      '%.nef',
      '%.nrw',
      '%.orf',
      '%.ori',
      '%.pef',
      '%.psd',
      '%.raf',
      '%.raw',
      '%.rw2',
      '%.rwl',
      '%.sr2',
      '%.srf',
      '%.srw',
      '%.x3f'
    ]::text[]
  )
  and exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $6
      and "asset_file"."isEdited" = $7
  )
  and "asset"."duplicateId" = $8::uuid
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."originalFileName",
  "asset"."type",
  "asset"."visibility",
  "asset"."stackId",
  "asset"."duplicateId",
  "asset"."localDateTime",
  "asset_exif"."fileSizeInByte",
  "asset_exif"."dateTimeOriginal",
  "asset_exif"."make",
  "asset_exif"."model",
  "asset_exif"."lensModel",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'preview'
      and "asset_file"."isEdited" = false
  ) as "previewPath"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."id" != $1::uuid
  and "asset"."ownerId" = $2::uuid
  and "asset"."type" = $3
  and "asset"."visibility" in ($4, $5)
  and "asset"."deletedAt" is null
  and "asset"."stackId" is null
  and lower(asset."originalFileName") like any (
    array[
      '%.jpg',
      '%.jpeg',
      '%.jpe',
      '%.png',
      '%.3fr',
      '%.ari',
      '%.arw',
      '%.cap',
      '%.cin',
      '%.cr2',
      '%.cr3',
      '%.crw',
      '%.dcr',
      '%.dng',
      '%.erf',
      '%.fff',
      '%.iiq',
      '%.k25',
      '%.kdc',
      '%.mrw',
      '%.nef',
      '%.nrw',
      '%.orf',
      '%.ori',
      '%.pef',
      '%.psd',
      '%.raf',
      '%.raw',
      '%.rw2',
      '%.rwl',
      '%.sr2',
      '%.srf',
      '%.srw',
      '%.x3f'
    ]::text[]
  )
  and exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $6
      and "asset_file"."isEdited" = $7
  )
  and "asset_exif"."dateTimeOriginal" >= $8
  and "asset_exif"."dateTimeOriginal" <= $9

-- DuplicateRepository.delete
update "asset"
set
  "duplicateId" = $1
where
  "ownerId" = $2
  and "duplicateId" = $3

-- DuplicateRepository.deleteAll
update "asset"
set
  "duplicateId" = $1
where
  "ownerId" = $2
  and "duplicateId" in ($3)

-- DuplicateRepository.search
begin
set
  local vchordrq.probes = 1
with
  "cte" as (
    select
      "asset"."id" as "assetId",
      "asset"."duplicateId",
      smart_search.embedding <=> $1 as "distance"
    from
      "asset"
      inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
    where
      "asset"."visibility" in ('archive', 'timeline')
      and "asset"."ownerId" = any ($2::uuid[])
      and "asset"."deletedAt" is null
      and "asset"."type" = $3
      and "asset"."id" != $4::uuid
      and "asset"."stackId" is null
    order by
      "distance"
    limit
      $5
  )
select
  *
from
  "cte"
where
  "cte"."distance" <= $6
commit

-- DuplicateRepository.merge
update "asset"
set
where
  (
    "duplicateId" = any ($1::uuid[])
    or "id" = any ($2::uuid[])
  )
